apex/agents/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from apex import db, bcrypt
from apex.models import Agent,Property
from apex.agents.forms import RegistrationForm, LoginForm, PropertyForm
from apex.agents.utils import save_profile_picture


agents = Blueprint('agents', __name__)

@agents.route("/admin/agents", methods=['GET', 'POST'])
def home_agent():
  # Fetch all properties for sale
  for_sale = Property.query.filter_by(listing_type='sale').all()

  # Fetch all properties for rent
  for_rent = Property.query.filter_by(listing_type='rent').all()

  return render_template("home_agent.html", for_sale=for_sale, for_rent=for_rent)

@agents.route("/admin/agents/register", methods=['GET', 'POST'])
def register():
  if current_user.is_authenticated:
    return redirect(url_for('agents.home_agent'))
  form = RegistrationForm()
  if form.validate_on_submit():
      hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
      agent = Agent(username=form.username.data, email=form.email.data, full_name=form.full_name.data, phone_number=form.phone_number.data, password=hashed_password)
      db.session.add(agent)
      db.session.commit()
      flash('Your account has been created! You are now able to log in', 'success')
      return redirect(url_for('agents.login'))
  return render_template('register.html', title='Register', form=form)

@agents.route("/admin/agents/login", methods=['GET', 'POST'])
def login():
      if current_user.is_authenticated:
          return redirect(url_for('agents.home_agent'))
      form = LoginForm()
      if form.validate_on_submit():
          agent = Agent.query.filter_by(email=form.email.data).first()
          if agent and bcrypt.check_password_hash(agent.password, form.password.data):
              login_user(agent, remember=form.remember.data)
              next_page = request.args.get('next')
              return redirect(next_page) if next_page else redirect(url_for('agents.home_agent'))
          else:
              flash('Login Unsuccessful. Please check email and password', 'danger')
      return render_template('login.html', title='Login', form=form)


@agents.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('agents.home_agent'))

# Route to add a new property
@agents.route("/admin/agents/add_property", methods=['GET', 'POST'])
@login_required
def add_property():
    form = PropertyForm()
    if form.validate_on_submit():
        # Extracting data from the form
        address = form.address.data
        city = form.city.data
        property_size = form.property_size.data
        num_bedrooms = form.num_bedrooms.data
        num_bathrooms = form.num_bathrooms.data
        num_carspaces = form.num_carspaces.data
        description = form.description.data
        image_link = form.image_link.data
        agent_id = current_user.id
        price = form.price.data
        listing_status = form.listing_status.data
        listing_type = form.listing_type.data

        # Creating a new Property object and adding it to the database
        property = Property(
            address=address,
            city=city,
            property_size=property_size,
            num_bedrooms=num_bedrooms,
            num_bathrooms=num_bathrooms,
            num_carspaces=num_carspaces,
            description=description,
            image_link=image_link,
            agent_id=agent_id,
            price=price,
            listing_status=listing_status,
            listing_type=listing_type
        )
        db.session.add(property)
        db.session.commit()

        flash('Property has been added successfully!', 'success')
        return redirect(url_for('agents.home_agent'))
    return render_template("add_property.html", title='Add Property', form=form)

@agents.route("/admin/agents/profile", methods=['GET', 'POST'])
@login_required
def view_profile():
    """
    This function is used to view the profile of the logged in agent."""
    return render_template('view_profile.html', title='My Profile')

@agents.route("/admin/agents/change_photo", methods=["POST"])
@login_required
def change_photo():
    if 'photo' in request.files:
        photo = request.files['photo']
        if photo.filename != '':
            picture_file = save_profile_picture(photo)
            current_user.profile_pic = picture_file
            db.session.commit()
            flash("Profile photo updated successfully", "success")
            return redirect(url_for("agents.view_profile"))
    flash("Failed to update profile photo. Please select a valid photo", "danger")

@agents.route("/admin/agents/change_password", methods=["POST"])
@login_required
def change_password():
    new_password = request.form.get("new_password")
    hashed_password = bcrypt.generate_password_hash(new_password).decode("utf-8")
    current_user.password = hashed_password
    db.session.commit()
    flash("Password changed successfully", "success")
    return redirect(url_for("agents.view_profile"))

@agents.route("/admin/agents/delete_account", methods=["POST"])
@login_required
def delete_account():
    db.session.delete(current_user)
    db.session.commit()
    flash("Your account has been deleted", "success")
    logout_user()
    return redirect(url_for("agents.home_agent"))


@agents.route("/admin/agents/my_ads", methods=['GET'])
@login_required
def my_ads():
    properties = Property.query.filter_by(agent_id=current_user.id).all()
    return render_template('my_ads.html', title='My Ads', properties=properties)


@agents.route("/admin/agents/property_details/<property_id>", methods=["GET", "POST"])
def property_details(property_id):
    """
    READ - Display ads individually with all data
    Displays the data and a specific ad by ID.
    The user's session is also checked so that the EDIT and DELETE buttons are
    rendered or not in the case of the ad owner.
    """
    # Check if there's a user logged in
    if current_user.is_authenticated:
        property_details = Property.query.filter_by(id=property_id).first()
        agent = current_user.username.upper()
        return render_template("property.html", property_details=property_details, agent=agent)

    # If no user is logged in
    property_details = Property.query.filter_by(id=property_id).first()
    return render_template("property.html", property_details=property_details)

@agents.route("/admin/agents/delete_property/<property_id>", methods=["GET", "POST"])
def delete_property(property_id):
  property_to_delete = Property.query.get(property_id)
  if property_to_delete:

      if current_user == property_to_delete.agent:
          # Deleting the property
          db.session.delete(property_to_delete)
          db.session.commit()
          flash('Property deleted successfully!', 'success')
      else:
          flash('You are not authorized to delete this property.', 'danger')
  else:
      flash('Property not found.', 'danger')

  return redirect(url_for('agents.home_agent')) 

@agents.route("/admin/agents/edit_property/<property_id>", methods=["GET", "POST"])
def edit_property(property_id):
  property_to_edit = Property.query.get(property_id)
  if property_to_edit:

      if current_user == property_to_edit.agent:
          if request.method == "POST":
              # Update property details
              property_to_edit.address = request.form['address']
              property_to_edit.price = request.form['price']
              property_to_edit.num_bedrooms = request.form['num_bedrooms']
              property_to_edit.num_bathrooms = request.form['num_bathrooms']
              property_to_edit.city = request.form['city']
              property_to_edit.listing_type = request.form['listing_type']
              property_to_edit.description = request.form['description']
              property_to_edit.listing_status = request.form['listing_status']

              # Check if an image link is provided
              if 'image_link' in request.form:
                  property_to_edit.image_link = request.form['image_link']
              # Commit the changes to the database
              db.session.commit()
              flash('Property updated successfully!', 'success')
              return redirect(url_for('agents.property_details', property_id=property_id))
          else:
              return render_template('edit_property.html', property_details=property_to_edit)
      else:
          flash('You are not authorized to edit this property.', 'danger')
          return redirect(url_for('agents.property_details', property_id=property_id))
  else:
      flash('Property not found.', 'danger')
      return redirect(url_for('agents.home_agent'))

@agents.route("/admin/agents/properties_list", methods=['GET', 'POST'])
def properties_list():
    # Get the selected option from the dropdown menu
    selected_option = request.form.get('listing_type')

    # Query properties based on the selected option
    if selected_option == 'For Sale':
        properties = Property.query.filter_by(listing_type='sale').all()
    elif selected_option == 'For Rent':
        properties = Property.query.filter_by(listing_type='rent').all()
    else:
        properties = Property.query.all()

    return render_template("properties_list.html", properties=properties, selected_option=selected_option)

@agents.route('/admin/agents/view_profile/add_description', methods=['POST'])
@login_required
def add_description():
    if request.method == 'POST':
        new_description = request.form.get('description')

        # Update the description attribute of the current agent
        current_user.description = new_description
        db.session.commit()

        flash('Description added successfully!', 'success')
        return redirect(url_for('agents.view_profile'))  # Redirect to the agent's profile page
    else:

apex/main/routes.py
from flask import render_template, Blueprint,request,redirect,url_for,flash
from apex.models import Property, Agent
from apex import mail
from flask_mail import Message
import os

main = Blueprint('main', __name__)

@main.route('/')
@main.route("/home")
def home():
    # Fetches the latest 3 properties
    latest_properties = Property.query.order_by(Property.id.desc()).limit(3).all()
  # Fetch all the Agents in the database.
    agents = Agent.query.all()

  
    return render_template('home.html', latest_properties=latest_properties, agents=agents, title='Home')

@main.route("/buy")
def buy():
    # Pagination Query to get the properties for sale
    page = request.args.get('page', 1, type=int)
    for_sale = Property.query.filter_by(listing_type='sale').paginate(page=page, per_page=5)
    # Query to get the total number of properties for sale
    total_properties_for_sale = Property.query.filter_by(listing_type='sale').count()
    return render_template('buy.html', for_sale=for_sale, total_properties_for_sale=total_properties_for_sale, title='Buy')

@main.route("/rent")
def rent():
    # Pagination Query to get the properties for rent
    page = request.args.get('page', 1, type=int)
    for_rent = Property.query.filter_by(listing_type='rent').paginate(page=page, per_page=5)
    # Query to get the total number of properties for rent
    total_properties_for_rent = Property.query.filter_by(listing_type='rent').count()
    return render_template('rent.html', for_rent=for_rent, total_properties_for_rent=total_properties_for_rent, title='Rent')

@main.route("/listings")
def listings():
    # pagination Query
    page = request.args.get('page', 1, type=int)
    all_properties = Property.query.paginate(page=page, per_page=5)
    # Query to get the total number of properties for rent
    total_properties = Property.query.count()
    return render_template('listings.html', all_properties=all_properties, total_properties=total_properties, title='Listings')

@main.route("/property_details/<property_id>", methods=['GET', 'POST'])
def property_details(property_id):
    property_details = Property.query.filter_by(id=property_id).first()

    if request.method == 'POST':
      # Get form data
      first_name = request.form['first_name']
      last_name = request.form['last_name']
      email = request.form['email']
      phone = request.form['phone']
      address = request.form['address']
      zip_code = request.form['zip_code']
      message = request.form['message']

      # The recipients email address
      EMAIL_USER = os.environ.get('EMAIL_USER')

      # Send email
      msg = Message(subject='Contact Form Submission',
                    sender= 'noreply@demo.com',
                    recipients=[EMAIL_USER])
      msg.body = f"""
      First Name: {first_name}
      Last Name: {last_name}
      Email: {email}
      Phone: {phone}
      address: {address}
      zip_code: {zip_code}
      Message:
      {message}
      """
      mail.send(msg)

      flash('Your message has been sent successfully!', 'success')
      return redirect(url_for('main.propery_details', property_id=property_id))


    return render_template('home_property_details.html', property_details=property_details, title='Property Details')


@main.route("/sell", methods=['GET', 'POST'])
def sell():

    if request.method == 'POST':
      # Get form data
      first_name = request.form['first_name']
      last_name = request.form['last_name']
      email = request.form['email']
      phone = request.form['phone']
      address = request.form['address']
      zip_code = request.form['zip_code']
      property_address = request.form['property_address']
      bathrooms = request.form['bathrooms']
      bedrooms = request.form['bedrooms']
      property_message = request.form['property_message']
      
      # The recipients email address
      EMAIL_USER = os.environ.get('EMAIL_USER')

      # Send email
      msg = Message(subject='Contact Form Submission',
                    sender= 'noreply@demo.com',
                    recipients=[EMAIL_USER])
      msg.body = f"""
      CONTACT DETAILS:
      First Name: {first_name}
      Last Name: {last_name}
      Email: {email}
      Phone: {phone}
      address: {address}
      zip_code: {zip_code}
      
      PROPERTY DETAILS:
      property_address: {property_address}
      bathrooms: {bathrooms}
      bedrooms: {bedrooms}
      Message:
      {property_message}
      """
      mail.send(msg)

      flash('Your message has been sent successfully!', 'success')
      return redirect(url_for('main.sell'))
  
    return render_template('sell.html', title='Sell')

@main.route("/about")
def about():
    return render_template('about.html', title='About')

@main.route("/agent_details/<agent_id>", methods=['GET', 'POST'])
def agent_details(agent_id):
    agent_details = Agent.query.filter_by(id=agent_id).first()

    if request.method == 'POST':
      # Get form data
      full_name = request.form['full_name']
      email = request.form['email']
      phone = request.form['phone']
      message = request.form['message']
      EMAIL_USER = agent_details.email

      # Send email
      msg = Message(subject='Contact Form Submission',
                    sender= 'noreply@demo.com',
                    recipients=[EMAIL_USER])
      msg.body = f"""
      Full Name: {full_name}
      Email: {email}
      Phone: {phone}
      Message:
      {message}
      """
      mail.send(msg)

      flash('Your message has been sent successfully!', 'success')
      return redirect(url_for('main.agent_details', agent_id=agent_id))
  
    return render_template('agent_details.html', agent_details=agent_details, title='Agent Details')


@main.route("/contact", methods=['GET', 'POST'])
def contact():
    if request.method == 'POST':
        # Get form data
        first_name = request.form['first_name']
        last_name = request.form['last_name']
        email = request.form['email']
        phone = request.form['phone']
        message = request.form['message']
        EMAIL_USER = os.environ.get('EMAIL_USER')

        # Send email
        msg = Message(subject='Contact Form Submission',
                      sender= 'noreply@demo.com',
                      recipients=[EMAIL_USER])
        msg.body = f"""
        First Name: {first_name}
        Last Name: {last_name}
        Email: {email}
        Phone: {phone}
        Message:
        {message}
        """
        mail.send(msg)

        flash('Your message has been sent successfully!', 'success')
        return redirect(url_for('main.contact'))

    return render_template('contact.html', title='Contact')

apex/templates/partials/cards.html
<div class="col-md-6 col-lg-4">
    <a href="{{ url_for('agents.property_details', property_id=property.id) }}">
        <div class="card-box">
            <div class="card-img">
                {% if property.image_link %}
                <img src="{{ property.image_link }}" class="img-fluid property-img" alt="Property Image">
                {% else %}
                <img src="{{ url_for('static', filename='no-image.png') }}" class="img-fluid property-img"
                    alt="Property Image">
                {% endif %}
            </div>

            <div class="card-description-box">
                <div class="row card-address-box">
                    <span>{{ property.address }}</span>
                </div>
                <div class="row card-city-box">
                    <span>{{ property.city }}</span>
                </div>
                <div class="row card-price-box">
                    <span class="card-type">
                        {% if property.listing_type == 'rent' %}
                        For Rent -
                        {% else %}
                        For Sale -
                        {% endif %}
                    </span>
                    <span class="card-price">
                        ${{ property.price }} {% if property.listing_type == 'rent' %}per month{% endif %}
                    </span>
                </div>
                <div class="container card-footer-box">
                    <div class="row card-bed-box">
                        <i class="fas fa-bed bed-icon"></i>
                        <div class="bed-info">{{property.num_bedrooms}}</div>
                    </div>
                    <div class="row card-bath-box">
                        <i class="fas fa-bath bath-icon"></i>
                        <div class="bath-info">{{property.num_bathrooms}}</div>
                    </div>
                </div>
            </div>
        </div>
    </a>
</div>

apex/templates/partials/footer.html
<!-- Footer -->
<div class="footer-main">

  <div class="container">

    <!-- Social media buttons -->
    <ul class="list-unstyled list-inline text-center social-buttons">
      <li class="list-inline-item">
        <a class="fab fa-facebook fa-lg mx-1" href="https://www.facebook.com/"></a>
      </li>
      <li class="list-inline-item">
        <a class="fab fa-twitter fa-lg mx-1" href="https://twitter.com/"></a>
      </li>
      <li class="list-inline-item">
        <a class="fab fa-linkedin-in fa-lg mx-1" href="https://www.linkedin.com/"></a>
      </li>
    </ul>


  </div>

  <!-- Copyright -->
  <div class="footer-copyright text-center">© 2024 Copyright: Apex Real Estate</div>
</div>

apex/templates/partials/home_cards.html
<div class="col-md-6 col-lg-4">
    <a href="{{ url_for('main.property_details', property_id=property.id) }}">
        <div class="card-box">
            <div class="card-img">
                {% if property.image_link %}
                <img src="{{ property.image_link }}" class="img-fluid property-img" alt="Property Image">
                {% else %}
                <img src="{{ url_for('static', filename='no-image.png') }}" class="img-fluid property-img"
                    alt="Property Image">
                {% endif %}
            </div>

            <div class="card-description-box">
                <div class="row card-address-box">
                    <span>{{ property.address }}</span>
                </div>
                <div class="row card-city-box">
                    <span>{{ property.city }}</span>
                </div>
                <div class="row card-price-box">
                    <span class="card-type">
                        {% if property.listing_type == 'rent' %}
                        For Rent -
                        {% else %}
                        For Sale -
                        {% endif %}
                    </span>
                    <span class="card-price">
                        ${{ property.price }} {% if property.listing_type == 'rent' %}per month{% endif %}
                    </span>
                </div>
                <div class="container card-footer-box">
                    <div class="row card-bed-box">
                        <i class="fas fa-bed bed-icon"></i>
                        <div class="bed-info">{{property.num_bedrooms}}</div>
                    </div>
                    <div class="row card-bath-box">
                        <i class="fas fa-bath bath-icon"></i>
                        <div class="bath-info">{{property.num_bathrooms}}</div>
                    </div>
                </div>
            </div>
        </div>
    </a>
</div>

apex/templates/partials/home_navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary py-0">
  <div class="container-fluid">
    <!-- Logo -->
    <a class="navbar-brand" href="{{ url_for('main.home') }}">
      <img src="https://i.imgur.com/5p44rDg.png" alt="Logo" width="150" height="auto">
    </a>
    <!-- Navbar Toggler Button -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Navigation links -->
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link fs-4 mx-3" href="{{ url_for('main.buy') }}">Buy</a>
        <a class="nav-link fs-4 mx-3" href="{{ url_for('main.rent') }}">Rent</a>
        <a class="nav-link fs-4 mx-3" href="{{ url_for('main.sell') }}">Sell</a>
        
        <a class="nav-link fs-4 mx-3" href="{{ url_for('main.about') }}">About</a>
        <a class="nav-link fs-4 mx-3" href="{{ url_for('main.contact') }}">Contact</a>
      </div>
    </div>
  </div>
</nav>

apex/templates/partials/navbar.html
<!-- Navbar -->
<nav class="navbar navbar-expand-md navbar-light bg-light  navbar-color">
    <a class="navbar-brand" href="{{ url_for('agents.home_agent') }}">
      <img src="https://i.imgur.com/5p44rDg.png" alt="Logo" width="100" height="auto">
    </a>
    <button class="navbar-toggler text-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
        aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse text-right" id="navbarsExampleDefault">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('agents.home_agent') }}" }}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('agents.properties_list') }}">All Properties</a>
            </li>
            <!-- Check if there is a user logged in and show personal page -->
          {% if current_user.is_authenticated %}

            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('agents.add_property') }}">Add a Property</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('agents.my_ads') }}">My Ads</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('agents.view_profile') }}">Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('agents.logout') }}">Logout</a>
            </li>

            <!-- If there's no user logged in session this links will be display -->
            {% else %}

            <li class="nav-item p-0">
                <a class="nav-link" href="{{ url_for('agents.register') }}">Create Account</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('agents.login') }}">Login</a>
            </li>
        </ul>
        {% endif %}

    </div>

</nav>

apex/templates/partials/no_results.html
<div class="container col-11 col-md-9 no-result-box">
    <div class="no-result-text">You haven't added any properties to your list of ads yet.</div>
    <div class="row col-8 col-md-6 col-xl-4 no-result-image-box">
        <img src="{{ url_for('static', filename='no-result.jpg') }}" class="img-fluid no-result-img"
            alt="Property Image">
    </div>
    <div class="container">
        <div class="no-result-buttons-box">
            <div class="col-11 col-md-6 no-result-buttons">
                <a href={{ url_for( 'agents.add_property') }}>
                    <button type="button" class="btn btn-dark btn-block btn-sm mx-auto" data-toggle="modal"
                        data-target="#agent_delete_account">Add a Property</button></a>
            </div>
            <div class="col-11 col-md-6 no-result-buttons">
                <a href={{ url_for( 'agents.home_agent' ) }}>
                    <button type="button" class="btn btn-dark btn-block btn-sm mx-auto" data-toggle="modal"
                        data-target="#agent_delete_account">Back to home</button></a>
            </div>
        </div>
    </div>
</div>